### PR TITLE
Fix baud rate option and add help/usage message

### PR DESCRIPTION
**Pull request by zcsahok**
Fixed `-b` option. It was neither defined nor later on used.

Added help and usage text. Took it from the comments at the top of the file. Maybe they could be removed then to avoid duplication.

Changed default WPM to 24 as per documentation.

Not sure about the versioning, is `1.0.8   05 Feb 2018` correct?

### CODE REVIEW

**Comment by N0NB** [comment]
Good catch, Zoli.

As for the version number, it hasn't been advanced for a while and it would probably be good to do so.

It may be over kill for this script, but there is a Perl module, Pod::Usage that I used in https://github.com/Hamlib/Hamlib/blob/master/tests/testctld.pl in Hamlib.  Feel free to use that if you'd like and bump the version.  Or we can go with just this patch and add another commit that bumps the version and the date.

73, Nate

**Comment by zcsahok** [comment]
As there are no releases (yet) let's just bump version number to 1.0.9

Thanks for the `pod2usage` pointer. I'm investigating now using POD both for usage and man page to have a common place for documentation.
Will commit as soon as I get something reasonable.

**Comment by zcsahok** [comment]
Converted man page contents to POD. Man page can be generated with
```
pod2man --center="K1EL keyer driver" --date="2019-12-30" src/winkeydaemon
```

If this is fine then the one checked in can be removed or overwritten.
Usage text is now just a one liner, but `-h` provides option details.

POD is split into synopsis+options (in the beginning of the file) and the details (at the end of the file). I find that this mimics better the original (now removed) source comments.

**Comment by N0NB** [comment]
The separate man page is likely left over from back when this was packaged in Debian as Debian considers it a bug for executables not to have a man page.  I just tried the pod2man utility and the resulting man page looks just fine.  As this script is not packaged by Debian, I think you can safely remove the old man page and its directory.  Or, if you prefer, I can do it as well.

**Comment by N0NB** [comment]
Rather than delete the old man page, simply replace it with the one generated from pod2man!

**Comment by zcsahok** [comment]
OK, updated man page and embedded the command to re-create it into the script.

**Comment by N0NB** [comment]
Looks good to me!  I'll push it and tag it as 1.0.9.  Thanks, Zoli!

**Pull request merged**
